server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix: /springhealth # 前缀应该放在zuul下，而不是routes下
  ignored-services: userservice
  routes:
    userservice:
      path: /user/**
      serviceId: userservice
#  host:
#    connect-timeout-millis: 5000  # 连接超时设置为5秒
#    socket-timeout-millis: 60000  # 读取超时设置为60秒

spring:
  zipkin:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "routes"
