spring:
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
  zipkin:
    baseUrl:  http://localhost:9411

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost


security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/userinfo