server:
  port: 8761

eureka:
  instance:
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: http://eureka2:8762/eureka/

spring:
  application:
    name: eureka-server1

# java -jar eureka-server.jar --spring.profiles.active=eureka1

# 在 Program Arguments 中添加 --spring.profiles.active=eureka1

# java -jar myapp.jar --server.port=8081