server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info  # 显式启用 `gateway` 相关的端点

spring:
  cloud:
    gateway:
      routes:
        - id: userservice-route
          uri: lb://userservice  # 使用服务发现访问 userservice
          predicates:
            - Path=/springhealth/user/**
          filters:
            - RewritePath=/springhealth/user/(?<remaining>.*), /${remaining}  # 转发时去除前缀 /springhealth/user

        - id: interventionroute
          uri: lb://interventionservice
          predicates:
            - Path=/springhealth/intervention/**
          filters:
            - RewritePath=/springhealth/intervention/(?<path>.*), /${path}
  zipkin:
    enabled: false


#    http://localhost:5555/actuator/gateway/routes
#    http://localhost:5555/actuator/health